# Generated by Django 3.0.6 on 2020-05-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doubts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('subject', models.CharField(choices=[('M', 'Mathematics'), ('P', 'Physics'), ('C', 'Chemistry')], default='C', max_length=1)),
                ('hardness_points', models.IntegerField(default=0)),
                ('date_asked', models.DateTimeField(auto_now_add=True, verbose_name='Date Asked')),
                ('no_of_answers', models.IntegerField(default=0)),
                ('asker', models.ForeignKey(on_delete=models.SET(doubts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('downvotes_total', models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL)),
                ('upvotes_total', models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_answered', models.DateTimeField(auto_now_add=True, verbose_name='Date Answered')),
                ('upvotes', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.SET(doubts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('downvoters', models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubts.Question')),
                ('upvoters', models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
