# Generated by Django 3.0.6 on 2020-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('M', 'Mathematics'), ('P', 'Physics'), ('C', 'Chemistry'), ('CS', 'Computer Science')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
