# Generated by Django 3.0.5 on 2020-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
