# Generated by Django 3.0.5 on 2020-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200501_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
